### ISSUE TITLE
[Router] History stores consecutive visits to the same path

### ISSUE THREAD

**Issue by davenotik** [baseloop/baseloop#2]
**Describe the bug**
Router seems to be tracking consecutive visits to the same path, so that navigating history will step through every such instance. I think what we want instead is for consecutive visits to the same path to show just once in history.

**To Reproduce**
1. Load website.
2. Click on Docs in nav.
3. Click docs foo link, then click docs bar link several times.
4. Hit the back button and you'll have to go through each docs bar visit before seeing docs foo. To the user, this looks like nothing is happening.

**Expected behavior**
It should go back to docs foo.

**Comment by kaisellgren** [comment]
Interestingly, this is the behavior of react-router :) even on their docs it does this. I think what it should do is just ignore the action when you try to navigate to the same URL
