### ISSUE TITLE
Receiving Upgrade Required error when running example project

### ISSUE THREAD

**Issue by karan15234** [baseloop/baseloop#29]
Hi,

While following the https://baseloop.dev/docs/installation documentation to run the example project, we are running into the following issue:

ERROR in ./node_modules/@baseloop/router/dist/es2015/router.js
Module not found: Error: Can't resolve '@baseloop/atom' in '/workplace/kkhurana/baseloop-test/node_modules/@baseloop/router/dist/es2015'
 @ ./node_modules/@baseloop/router/dist/es2015/router.js 7:0-38 15:26-30 17:23-27 18:31-35 19:30-34
 @ ./node_modules/@baseloop/router/dist/es2015/index.js
 @ ./src/common/app/app-controller.ts
 @ ./src/client/index.ts

The website (http://localhost:3456) shows 'Upgrade Required' error.

**Comment by kaisellgren** [comment]
The script that creates an example project from scratch is out-of-date. The best example would be this repository: https://github.com/baseloop/baseloop-example

I'll fix the documentation to point this out.
