### ISSUE TITLE
[Router] Back is broken after visiting 404 from non-root path

### ISSUE THREAD

**Issue by davenotik** [baseloop/baseloop#3]
**Describe the bug**
Going back after hitting the intentional 404 link does not resolve the route and gives an error e.g. `Cannot GET /docs/foo` instead. Home to 404 and back does work, however.

**To Reproduce**
1. Load website.
2. Hit Docs.
3. Go Back.
4. See error `Cannot GET /docs`.

**Expected behavior**
Loads proper page.

**Comment by kaisellgren** [comment]
This is because you are using your webpack-dev-server and not the server I created. This is the precise reason why I created the server app (for SPA reload purposes). The basic server does not understand that there's no such thing as `/docs`, and instead it has to serve the root `index.html`.

**Comment by kaisellgren** [comment]
You can use baseloop-dev-server now, it's part of `@baseloop/dev`, pull latest changes and do `lerna bootstrap --hoist` and then run the script under website folder.
